const API = localStorage.getItem("cleancred_api") || "http://127.0.0.1:8000";
let stream=null, qrStream=null, session=null;
const $=id=>document.getElementById(id);
function headers(){return session?{"Authorization":"Bearer "+session.token}:{};}
async function api(path,opt={}){opt.headers={...headers(),...(opt.headers||{})};const r=await fetch(API+path,opt);const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={detail:t}}if(!r.ok)throw new Error(d.detail||`HTTP ${r.status}`);return d;}
function out(id,x){$(id).textContent=typeof x==="string"?x:JSON.stringify(x,null,2)}
function err(id,e){out(id,"⚠ "+e.message)}
function requireRole(role){if(!session)throw new Error("Sign in first");if(session.user.role!==role)throw new Error(`Sign in as ${role}`)}
function badge(){ $("sessionBadge").textContent=session?`${session.user.name} · ${session.user.role} · ${session.user.points} credits`:"Not signed in"; }
async function createUser(){try{const d=await api("/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$('newName').value,role:$('newRole').value,pin:$('newPin').value})});out("authResult",d);$('loginId').value=d.id}catch(e){err("authResult",e)}}
async function login(){try{const d=await api("/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({user_id:Number($('loginId').value),pin:$('loginPin').value})});session={token:d.access_token,user:d.user};badge();out("authResult",{message:"Signed in",user:d.user});loadLeaderboard();if(d.user.role==='admin')loadAnalytics();}catch(e){err("authResult",e)}}
function logout(){session=null;badge();out("authResult","Signed out")}
async function startCamera(){try{requireRole('citizen');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('camera').srcObject=stream}catch(e){alert(e.message)}}
function position(){return new Promise((res,rej)=>navigator.geolocation?navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:15000,maximumAge:0}):rej(new Error('GPS unavailable')))}
async function captureAndReport(){try{requireRole('citizen');if(!stream)throw new Error('Start camera first');const v=$('camera'),c=$('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.88));const p=await position();const fd=new FormData();fd.append('category',$('category').value);fd.append('latitude',p.coords.latitude);fd.append('longitude',p.coords.longitude);fd.append('image',blob,'camera-capture.jpg');const d=await api('/reports',{method:'POST',body:fd});out('reportResult',d);['verifyReportId','collectReportId','timelineId'].forEach(x=>$(x).value=d.report_id)}catch(e){err('reportResult',e)}}
async function workerVerify(){try{requireRole('worker');const p=await position(),id=Number($('verifyReportId').value);const d=await api('/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({report_id:id,segregated:$('segregated').value==='true',worker_lat:p.coords.latitude,worker_lon:p.coords.longitude})});out('verifyResult',d);$('collectReportId').value=id;$('timelineId').value=id;$('qrToken').value=d.qr_token;$('qrBox').innerHTML='';new QRCode($('qrBox'),{text:d.qr_token,width:190,height:190});$('scoreCard').classList.remove('hidden');$('scoreValue').textContent=d.verification_score;$('riskValue').textContent=`${d.risk_level} RISK`;$('heroScore').textContent=d.verification_score;loadTimeline()}catch(e){err('verifyResult',e)}}
async function startQRScanner(){try{requireRole('worker');if(!('BarcodeDetector'in window))throw new Error('QR camera scanning is unavailable in this browser. Paste the one-time token instead.');qrStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});const v=$('qrCamera');v.hidden=false;v.srcObject=qrStream;const detector=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{if(v.readyState>=2){const c=await detector.detect(v);if(c.length){$('qrToken').value=c[0].rawValue;qrStream.getTracks().forEach(t=>t.stop());v.hidden=true;return}}requestAnimationFrame(loop)};requestAnimationFrame(loop)}catch(e){alert(e.message)}}
async function collect(){try{requireRole('worker');const p=await position(),id=Number($('collectReportId').value);const d=await api('/collect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({report_id:id,qr_token:$('qrToken').value,worker_lat:p.coords.latitude,worker_lon:p.coords.longitude})});out('collectResult',d);$('heroScore').textContent='✓';loadTimeline()}catch(e){err('collectResult',e)}}
async function loadTimeline(){try{if(!session)throw new Error('Sign in first');const id=Number($('timelineId').value);const d=await api(`/reports/${id}/timeline`);$('timeline').innerHTML=d.events.map(e=>`<div class="event"><span class="dot"></span><div><b>${e.stage}</b><small>${new Date(e.time).toLocaleString()}</small><p>${e.status} · ${e.detail}</p></div></div>`).join('')}catch(e){$('timeline').innerHTML=`<p class="muted">${e.message}</p>`}}
async function loadAnalytics(){try{requireRole('admin');const d=await api('/analytics');$('mReports').textContent=d.totals.reports;$('mVerified').textContent=d.totals.verified;$('mCollected').textContent=d.totals.collected;$('mRate').textContent=d.collection_rate+'%';$('mCredits').textContent=d.totals.credits;$('risks').innerHTML=d.risk_distribution.map(x=>`<div class="barrow"><span>${x.risk_level}</span><b>${x.count}</b></div>`).join('')||'<span>—</span>';$('categories').innerHTML=d.categories.map(x=>`<div class="barrow"><span>${x.category}</span><b>${x.count}</b></div>`).join('')||'<span>—</span>';$('hotspots').innerHTML=d.hotspots.length?d.hotspots.map(x=>`<div class="hotspot"><b>${x.reports} reports</b><span>${x.lat}, ${x.lon}</span></div>`).join(''):'<p class="muted">No recurring hotspot detected yet.</p>';const rows=await api('/reports');out('reports',rows)}catch(e){err('reports',e)}}
async function loadLeaderboard(){try{const d=await api('/leaderboard');$('leaderboard').innerHTML=d.length?d.map((x,i)=>`<div class="rank"><b>#${i+1}</b><span>${x.name}</span><strong>${x.points} GC</strong></div>`).join(''):'<p class="muted">No citizen activity yet.</p>'}catch(e){$('leaderboard').innerHTML=`<p class="muted">${e.message}</p>`}}
loadLeaderboard();badge();
